/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import java.util.ArrayList;
import backend.Inventory;
import backend.Employee;
import backend.User;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tomsm
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    
    Inventory inv = null;
    Employee emp  = null;
    User usr = null;
    
    DefaultTableModel inventoryModel;
    DefaultTableModel employeeModel;
    
    String currentUser = "";
    
    
    public Client() {
        initComponents();
//        handler = new Handler();
        inv = new Inventory();
        inventoryModel = (DefaultTableModel) inventoryTable.getModel();
        emp = new Employee();
        employeeModel = (DefaultTableModel) employeeTable.getModel();
        usr = new User();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        userSelectionPanel = new javax.swing.JPanel();
        userSelectionTitle = new javax.swing.JLabel();
        userSelectionInfo = new javax.swing.JLabel();
        restaurantStaffButton = new javax.swing.JButton();
        deliveryStaffButton = new javax.swing.JButton();
        restaurantLoginPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deliveryLoginPanel = new javax.swing.JPanel();
        restaurantPanel = new javax.swing.JPanel();
        restaurantTabs = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        restarauntLabel1 = new javax.swing.JLabel();
        doorStatusButton1 = new javax.swing.JButton();
        inventoryButton1 = new javax.swing.JButton();
        employeeButton1 = new javax.swing.JButton();
        notificationButton1 = new javax.swing.JButton();
        doorStatusPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        inventoryPanel = new javax.swing.JPanel();
        backButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        updateInventoryButton = new javax.swing.JButton();
        employeePanel = new javax.swing.JPanel();
        backButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        updateEmployeeButton = new javax.swing.JButton();
        notificationsPanel = new javax.swing.JPanel();
        backButton1 = new javax.swing.JButton();
        headChefPanel = new javax.swing.JPanel();
        haedChefAdminTitle = new javax.swing.JLabel();
        createNewUserLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newUserNameInput = new javax.swing.JTextField();
        newUserPasswordInput = new javax.swing.JTextField();
        createNewUserButton = new javax.swing.JButton();
        createNewUserStatus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newUserRoleInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userSelectionTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userSelectionTitle.setText("Future Fridges");

        userSelectionInfo.setText("Please select your user type to be taken to the login page:");

        restaurantStaffButton.setText("Restaurant Staff");
        restaurantStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurantStaffButtonActionPerformed(evt);
            }
        });

        deliveryStaffButton.setText("Delivery Staff");
        deliveryStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryStaffButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userSelectionPanelLayout = new javax.swing.GroupLayout(userSelectionPanel);
        userSelectionPanel.setLayout(userSelectionPanelLayout);
        userSelectionPanelLayout.setHorizontalGroup(
            userSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userSelectionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliveryStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(userSelectionPanelLayout.createSequentialGroup()
                            .addComponent(restaurantStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userSelectionPanelLayout.createSequentialGroup()
                            .addGroup(userSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(userSelectionInfo)
                                .addComponent(userSelectionTitle))
                            .addGap(412, 412, 412)))))
        );
        userSelectionPanelLayout.setVerticalGroup(
            userSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userSelectionTitle)
                .addGap(18, 18, 18)
                .addComponent(userSelectionInfo)
                .addGap(57, 57, 57)
                .addComponent(restaurantStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(deliveryStaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        tabbedPane.addTab("User Selection", userSelectionPanel);

        usernameLabel.setText("Username:");

        passwordLabel.setText("Password:");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Restaurant Login:");

        javax.swing.GroupLayout restaurantLoginPanelLayout = new javax.swing.GroupLayout(restaurantLoginPanel);
        restaurantLoginPanel.setLayout(restaurantLoginPanelLayout);
        restaurantLoginPanelLayout.setHorizontalGroup(
            restaurantLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restaurantLoginPanelLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(restaurantLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginButton)
                    .addGroup(restaurantLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(restaurantLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(restaurantLoginPanelLayout.createSequentialGroup()
                                .addComponent(passwordLabel)
                                .addGap(18, 18, 18)
                                .addComponent(passwordInput))
                            .addGroup(restaurantLoginPanelLayout.createSequentialGroup()
                                .addComponent(usernameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        restaurantLoginPanelLayout.setVerticalGroup(
            restaurantLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restaurantLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(restaurantLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(restaurantLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Restaurant Login", restaurantLoginPanel);

        javax.swing.GroupLayout deliveryLoginPanelLayout = new javax.swing.GroupLayout(deliveryLoginPanel);
        deliveryLoginPanel.setLayout(deliveryLoginPanelLayout);
        deliveryLoginPanelLayout.setHorizontalGroup(
            deliveryLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );
        deliveryLoginPanelLayout.setVerticalGroup(
            deliveryLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Delivery Login", deliveryLoginPanel);

        restarauntLabel1.setText("Welcome to the restaurant homepage");

        doorStatusButton1.setText("Door Status");
        doorStatusButton1.setActionCommand("");
        doorStatusButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doorStatusButton1ActionPerformed(evt);
            }
        });

        inventoryButton1.setText("Inventory");
        inventoryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButton1ActionPerformed(evt);
            }
        });

        employeeButton1.setText("Employees");
        employeeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeButton1ActionPerformed(evt);
            }
        });

        notificationButton1.setText("Notifications");
        notificationButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(restarauntLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(doorStatusButton1)
                .addGap(66, 66, 66)
                .addComponent(inventoryButton1)
                .addGap(69, 69, 69)
                .addComponent(employeeButton1)
                .addGap(58, 58, 58)
                .addComponent(notificationButton1)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restarauntLabel1)
                .addGap(18, 18, 18)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doorStatusButton1)
                    .addComponent(inventoryButton1)
                    .addComponent(employeeButton1)
                    .addComponent(notificationButton1))
                .addContainerGap(406, Short.MAX_VALUE))
        );

        restaurantTabs.addTab("Home", home);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout doorStatusPanelLayout = new javax.swing.GroupLayout(doorStatusPanel);
        doorStatusPanel.setLayout(doorStatusPanelLayout);
        doorStatusPanelLayout.setHorizontalGroup(
            doorStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doorStatusPanelLayout.createSequentialGroup()
                .addContainerGap(712, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );
        doorStatusPanelLayout.setVerticalGroup(
            doorStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doorStatusPanelLayout.createSequentialGroup()
                .addContainerGap(440, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );

        restaurantTabs.addTab("Door Status", doorStatusPanel);

        backButton2.setText("Back");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity", "Expiry Date", "Days Till Expiry Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(inventoryTable);

        updateInventoryButton.setText("Update");
        updateInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInventoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventoryPanelLayout = new javax.swing.GroupLayout(inventoryPanel);
        inventoryPanel.setLayout(inventoryPanelLayout);
        inventoryPanelLayout.setHorizontalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateInventoryButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        inventoryPanelLayout.setVerticalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateInventoryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton2)
                .addContainerGap())
        );

        restaurantTabs.addTab("Inventory", inventoryPanel);

        backButton3.setText("Back");
        backButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton3ActionPerformed(evt);
            }
        });

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Role", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(employeeTable);

        updateEmployeeButton.setText("Update");
        updateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout employeePanelLayout = new javax.swing.GroupLayout(employeePanel);
        employeePanel.setLayout(employeePanelLayout);
        employeePanelLayout.setHorizontalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateEmployeeButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        employeePanelLayout.setVerticalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateEmployeeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(backButton3)
                .addContainerGap())
        );

        restaurantTabs.addTab("Employees", employeePanel);

        backButton1.setText("Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout notificationsPanelLayout = new javax.swing.GroupLayout(notificationsPanel);
        notificationsPanel.setLayout(notificationsPanelLayout);
        notificationsPanelLayout.setHorizontalGroup(
            notificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificationsPanelLayout.createSequentialGroup()
                .addContainerGap(712, Short.MAX_VALUE)
                .addComponent(backButton1)
                .addContainerGap())
        );
        notificationsPanelLayout.setVerticalGroup(
            notificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificationsPanelLayout.createSequentialGroup()
                .addContainerGap(440, Short.MAX_VALUE)
                .addComponent(backButton1)
                .addContainerGap())
        );

        restaurantTabs.addTab("Notifications", notificationsPanel);

        haedChefAdminTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        haedChefAdminTitle.setText("Head Chef Admin Page");

        createNewUserLabel.setText("Create New User");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        createNewUserButton.setText("Submit");
        createNewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewUserButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Role");

        newUserRoleInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserRoleInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headChefPanelLayout = new javax.swing.GroupLayout(headChefPanel);
        headChefPanel.setLayout(headChefPanelLayout);
        headChefPanelLayout.setHorizontalGroup(
            headChefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headChefPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(headChefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(headChefPanelLayout.createSequentialGroup()
                        .addComponent(createNewUserStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createNewUserButton))
                    .addGroup(headChefPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(newUserNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(createNewUserLabel)
                    .addComponent(haedChefAdminTitle)
                    .addGroup(headChefPanelLayout.createSequentialGroup()
                        .addGroup(headChefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(headChefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newUserPasswordInput)
                            .addComponent(newUserRoleInput))))
                .addContainerGap(512, Short.MAX_VALUE))
        );
        headChefPanelLayout.setVerticalGroup(
            headChefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headChefPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(haedChefAdminTitle)
                .addGap(18, 18, 18)
                .addComponent(createNewUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headChefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newUserNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headChefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newUserPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(headChefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headChefPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(headChefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(newUserRoleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(createNewUserStatus))
                    .addGroup(headChefPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(createNewUserButton)))
                .addContainerGap(305, Short.MAX_VALUE))
        );

        restaurantTabs.addTab("Head Chef Admin", headChefPanel);

        javax.swing.GroupLayout restaurantPanelLayout = new javax.swing.GroupLayout(restaurantPanel);
        restaurantPanel.setLayout(restaurantPanelLayout);
        restaurantPanelLayout.setHorizontalGroup(
            restaurantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restaurantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restaurantTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        restaurantPanelLayout.setVerticalGroup(
            restaurantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restaurantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(restaurantTabs)
                .addContainerGap())
        );

        tabbedPane.addTab("Restaurant Page", restaurantPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restaurantStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurantStaffButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Taking you to the restaurant staff login page");
        tabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_restaurantStaffButtonActionPerformed

    private void deliveryStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryStaffButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Taking you to the delivery staff login page");
        tabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_deliveryStaffButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String username = usernameInput.getText().toString();
        String password = passwordInput.getText().toString();
        
        // Connect to database and check details against the user
        
        System.out.println(username);
        System.out.println(password);
        
        if (usr.login(username, password).equals("authenticated")) {
            System.out.println("Successful login");
            currentUser = username;
            tabbedPane.setSelectedIndex(3);
        } else {
            System.out.println("Incorrect username/password");
        }
        
//        if (username.equals("test") & password.equals("test")) {
//            tabbedPane.setSelectedIndex(3);
//        }
        
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void doorStatusButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doorStatusButton1ActionPerformed
        // TODO add your handling code here:
        restaurantTabs.setSelectedIndex(1);
    }//GEN-LAST:event_doorStatusButton1ActionPerformed

    private void inventoryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButton1ActionPerformed
        // TODO add your handling code here:
        restaurantTabs.setSelectedIndex(2);
    }//GEN-LAST:event_inventoryButton1ActionPerformed

    private void employeeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeButton1ActionPerformed
        // TODO add your handling code here:
        restaurantTabs.setSelectedIndex(3);
    }//GEN-LAST:event_employeeButton1ActionPerformed

    private void notificationButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationButton1ActionPerformed
        // TODO add your handling code here:
        restaurantTabs.setSelectedIndex(4);
    }//GEN-LAST:event_notificationButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        restaurantTabs.setSelectedIndex(0);
    }//GEN-LAST:event_backButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        restaurantTabs.setSelectedIndex(0);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        // TODO add your handling code here:
        restaurantTabs.setSelectedIndex(0);
    }//GEN-LAST:event_backButton2ActionPerformed

    private void backButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton3ActionPerformed
        // TODO add your handling code here:
        restaurantTabs.setSelectedIndex(0);
    }//GEN-LAST:event_backButton3ActionPerformed

    private void updateInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInventoryButtonActionPerformed
        // TODO add your handling code here:
        // Send a request to the database and update the table in the following      
        ArrayList<HashMap<String, String>> data = inv.getAllInventory();
        for (int i = 0; i < data.size(); i++) {
            HashMap<String, String> c = data.get(i);
            inventoryModel.addRow(new Object[]{i, c.get("name"), c.get("qty"), c.get("date")});
        }
        
    }//GEN-LAST:event_updateInventoryButtonActionPerformed

    private void updateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<HashMap<String, String>> data = emp.getAllEmployee();
        for (int i = 0; i < data.size(); i++) {
            HashMap<String, String> c = data.get(i);
            employeeModel.addRow(new Object[]{i, c.get("name"), c.get("role"), c.get("date")});
        }
    }//GEN-LAST:event_updateEmployeeButtonActionPerformed

    private void createNewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewUserButtonActionPerformed
        // TODO add your handling code here:
        String username = newUserNameInput.getText();
        String password = newUserPasswordInput.getText();
        String role = newUserRoleInput.getText();
        
        // Make sure the head chef is currently logged in first
        System.out.println(usr.currentUserIsHeadChef(username, role));
        
        if (usr.currentUserIsHeadChef(username, role).equals("true")) {
            String result = usr.createNewUser(username, password, role);
            createNewUserStatus.setText(result);
        } else {
            createNewUserStatus.setText("Current user is not a head chef, so cannot create new users");
        }
        
        
    }//GEN-LAST:event_createNewUserButtonActionPerformed

    private void newUserRoleInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserRoleInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserRoleInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton backButton2;
    private javax.swing.JButton backButton3;
    private javax.swing.JButton createNewUserButton;
    private javax.swing.JLabel createNewUserLabel;
    private javax.swing.JLabel createNewUserStatus;
    private javax.swing.JPanel deliveryLoginPanel;
    private javax.swing.JButton deliveryStaffButton;
    private javax.swing.JButton doorStatusButton1;
    private javax.swing.JPanel doorStatusPanel;
    private javax.swing.JButton employeeButton1;
    private javax.swing.JPanel employeePanel;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel haedChefAdminTitle;
    private javax.swing.JPanel headChefPanel;
    private javax.swing.JPanel home;
    private javax.swing.JButton inventoryButton1;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField newUserNameInput;
    private javax.swing.JTextField newUserPasswordInput;
    private javax.swing.JTextField newUserRoleInput;
    private javax.swing.JButton notificationButton1;
    private javax.swing.JPanel notificationsPanel;
    private javax.swing.JTextField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel restarauntLabel1;
    private javax.swing.JPanel restaurantLoginPanel;
    private javax.swing.JPanel restaurantPanel;
    private javax.swing.JButton restaurantStaffButton;
    private javax.swing.JTabbedPane restaurantTabs;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JButton updateEmployeeButton;
    private javax.swing.JButton updateInventoryButton;
    private javax.swing.JLabel userSelectionInfo;
    private javax.swing.JPanel userSelectionPanel;
    private javax.swing.JLabel userSelectionTitle;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
